# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'Starter Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for Starter Project

  target 'Starter ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Starter ProjectUITests' do
    # Pods for testing
  end

end
